name: Publish to NuGet

on:
    release:
        types: [published]
    workflow_dispatch:
        inputs:
            version:
                description: "Version to publish (e.g., 0.1.0)"
                required: true

jobs:
    publish:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Setup .NET
              uses: actions/setup-dotnet@v3
              with:
                  dotnet-version: "10.0.x"
                  dotnet-quality: "preview"

            - name: Restore dependencies
              run: dotnet restore

            - name: Build
              run: dotnet build --configuration Release --no-restore

            - name: Test
              run: dotnet test --no-build --configuration Release --verbosity normal

            - name: Pack SumerUI
              run: dotnet pack src/lib/SumerUI.csproj --configuration Release --no-build --output ./artifacts

            - name: Pack SumerUI.Renderers
              run: dotnet pack src/renderers/SumerUI.Renderers.csproj --configuration Release --no-build --output ./artifacts

            - name: Pack SumerUI.Generators
              run: dotnet pack src/generators/SumerUI.Generators.csproj --configuration Release --no-build --output ./artifacts

            - name: Publish to NuGet
              run: dotnet nuget push ./artifacts/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
